#!/bin/bash

export MYSQL_DB_URL=jdbc:mysql://localhost:3306/blobdb

export MYSQL_DB_USERNAME=root

export MYSQL_DB_PASSWORD=12345


# export DO_STORAGE_KEY=DO00BRETV9PAJGD2QDPJ

# export DO_STORAGE_SECRETKEY=4JSY0zzM4jH5g4HBsdFzUzLlBWiyS3yhRyMkDYaNDSk

# export DO_STORAGE_BUCKETNAME=lmltfip2022

# export DO_STORAGE_ENDPOINT=sgp1.digitaloceanspaces.com

# export DO_STORAGE_ENDPOINT_REGION=sgp1


export DO_STORAGE_KEY=DO00AVHBCKCR3LBUU3QT

export DO_STORAGE_SECRETKEY=xNbNfGEMFx0SYIwE61ijAaf08Yh+hz0WI3x5wtxeGE4

export DO_STORAGE_BUCKETNAME=vajyitfip2022

export DO_STORAGE_ENDPOINT=sgp1.digitaloceanspaces.com

export DO_STORAGE_ENDPOINT_REGION=sgp1